# Generated by Django 6.0.1 on 2026-06-06 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('economy', '经济舱旅客'), ('business', '商务舱旅客'), ('first_class', '头等舱旅客'), ('investor', '投资者'), ('top_investor', '顶级投资者'), ('trainee_cabin_crew', '实习空乘'), ('trainee_first_officer', '实习副驾驶'), ('trainee_captain', '实习机长'), ('trainee_ground', '实习地勤'), ('cabin_crew', '正式空乘'), ('first_officer', '正式副驾驶'), ('captain', '正式机长'), ('ground_staff', '正式地勤'), ('admin', '管理员')], default='economy', max_length=30, verbose_name='角色')),
                ('miles', models.IntegerField(default=0, verbose_name='累计里程')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
