# Generated by Django 6.0.1 on 2026-06-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('economy', '经济舱旅客'), ('business', '商务舱旅客'), ('first_class', '头等舱旅客'), ('investor', '投资者'), ('uinv', '顶级投资者'), ('trainee_cabin_crew', '实习空乘'), ('trainee_first_officer', '实习副驾驶'), ('trainee_captain', '实习机长'), ('trainee_ground', '实习地勤'), ('cabin_crew', '正式空乘'), ('first_officer', '正式副驾驶'), ('captain', '正式机长'), ('ground_staff', '正式地勤'), ('admin', '管理员')], default='economy', max_length=30, verbose_name='角色'),
        ),
    ]
