# Generated by Django 6.0.1 on 2026-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qq_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('economy', '经济舱旅客'), ('business', '商务舱旅客'), ('first_class', '头等舱旅客'), ('investor', '投资者'), ('uinv', '顶级投资者'), ('trainee_cabin_crew', '实习空乘'), ('trainee_first_officer', '实习副驾驶'), ('trainee_captain', '实习机长'), ('trainee_ground', '实习地勤'), ('cabin_crew', '正式空乘'), ('first_officer', '正式副驾驶'), ('captain', '正式机长'), ('ground_staff', '正式地勤'), ('admin', '管理员'), ('hod', 'HOD-部门主管'), ('shr', 'SHR-高级管理'), ('vice_chairman', 'Vice Chairman-副董事长'), ('chairman', 'Chairman-董事长'), ('group_owner', 'Group Owner-集团所有者'), ('flight_host', 'Flight Host-飞行经理')], default='economy', max_length=30, verbose_name='角色'),
        ),
    ]
