# Generated by Django 6.0.1 on 2026-06-06 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='里程数')),
                ('type', models.CharField(choices=[('earn', '获得'), ('redeem', '消费')], default='earn', max_length=10, verbose_name='类型')),
                ('description', models.CharField(max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight', verbose_name='关联航班')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '里程记录',
                'verbose_name_plural': '里程记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
