# Generated by Django 6.0.1 on 2026-06-06 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('department', models.CharField(choices=[('flight_dept', '飞行部'), ('cabin_dept', '客舱部'), ('ground_dept', '地勤部'), ('ops_dept', '运控部'), ('admin_dept', '行政部')], max_length=20, verbose_name='部门')),
                ('location', models.CharField(default='新帆国际机场', max_length=100, verbose_name='工作地点')),
                ('job_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('volunteer', '志愿者')], default='volunteer', max_length=20, verbose_name='工作类型')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='开放申请')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '招聘职位',
                'verbose_name_plural': '招聘职位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='申请理由')),
                ('resume', models.TextField(verbose_name='个人经历')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewed', '已查看'), ('accepted', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting', verbose_name='职位')),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
