# Generated by Django 6.0.1 on 2026-06-06 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='航班号')),
                ('origin', models.CharField(max_length=100, verbose_name='出发地')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('departure_time', models.DateTimeField(verbose_name='计划起飞')),
                ('arrival_time', models.DateTimeField(verbose_name='计划到达')),
                ('aircraft', models.CharField(default='A320neo', max_length=50, verbose_name='机型')),
                ('gate', models.CharField(blank=True, max_length=10, null=True, verbose_name='登机口')),
                ('route_type', models.CharField(choices=[('domestic', '国内'), ('international', '国际')], default='domestic', max_length=20, verbose_name='航线类型')),
                ('status', models.CharField(choices=[('scheduled', '已排班'), ('boarding', '登机中'), ('departed', '已起飞'), ('arrived', '已到达'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '航班',
                'verbose_name_plural': '航班',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='FlightCrewSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', '机长'), ('first_officer', '副驾驶'), ('purser', '乘务长'), ('cabin_crew', '空乘'), ('ground_staff', '地勤')], max_length=20, verbose_name='报名角色')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_signups', to='flights.flight', verbose_name='航班')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_signups', to=settings.AUTH_USER_MODEL, verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '航班报名',
                'verbose_name_plural': '航班报名',
                'ordering': ['-signed_up_at'],
                'unique_together': {('flight', 'user')},
            },
        ),
    ]
