# Generated by Django 6.0.1 on 2026-06-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='私人航班'),
        ),
        migrations.CreateModel(
            name='PrivateFlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='航班号')),
                ('origin', models.CharField(max_length=100, verbose_name='出发地')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('departure_time', models.DateTimeField(verbose_name='计划起飞')),
                ('arrival_time', models.DateTimeField(verbose_name='计划到达')),
                ('aircraft', models.CharField(default='B737-800', max_length=50, verbose_name='机型')),
                ('route_type', models.CharField(choices=[('domestic', '国内'), ('international', '国际')], default='domestic', max_length=20, verbose_name='航线类型')),
                ('purpose', models.TextField(verbose_name='飞行目的')),
                ('passenger_count', models.PositiveIntegerField(default=1, verbose_name='乘客人数')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_flight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='flights.flight', verbose_name='创建的航班')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flight_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_flight_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '私人航班申请',
                'verbose_name_plural': '私人航班申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
