# Generated by Django 6.0.1 on 2026-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_is_private_privateflightrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.CharField(default='Boeing 737-800', max_length=50, verbose_name='机型'),
        ),
    ]
