# Generated by Django 6.0.1 on 2026-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态变更时间'),
        ),
    ]
